modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/TheIllusiveC4/MagicalPsi/issues"
logoFile="${mod_icon}"
license="CC-BY-NC-SA-4.0"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.magipsi]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magipsi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magipsi]]
    modId="psi"
    mandatory=true
    versionRange="[1.16-88,)"
    ordering="NONE"
    side="BOTH"
